-- Analytics Dashboard

DROP TABLE IF EXISTS insights;
CREATE TABLE insights
(
	customer_id int primary key,
	age	int,
	gender varchar(50),
	item_purchased varchar(50),
	category varchar(50),
	purchase_amount int,
	location varchar(100),
	size varchar(10),
	color varchar(50),
	season varchar(100),
	review_rating float,
	subscription_status	varchar(50),
	shipping_type	varchar(200),
	discount_applied varchar(100),
	previous_purchases	int,
	payment_method varchar(500),
	frequency_of_purchases	varchar(500),
	age_group	varchar(200),
	purchase_frequency_days int
);

SELECT * FROM insights limit 10;

-- Business Analysis

-- Q1. What is the total revenue generated by male vs. female customers?

select 
	gender, sum(purchase_amount) as revenue
from insights
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select 
	customer_id, purchase_amount
from insights
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from insights)

-- Q3. Which are the top 5 products with the highest average review rating?

select 
	item_purchased, 
	round(avg(review_rating::numeric),2) as average_Review_rating
from insights
group by item_purchased
order by average_review_rating desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select 
	shipping_type,
	round(avg(purchase_amount::numeric),4) as average_Purchase_Amount
from insights
where shipping_type in('Standard', 'Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select 
	count(customer_id) as Total_Customers, 
	subscription_status,
	round(avg(purchase_amount),2) as Average_Money_Spend,
	sum(purchase_amount) as Revenue
from insights
group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied? (Which products relay heavily on discounts for its sell.)

select 
	item_purchased,
	round(100.0*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from insights
group by item_purchased
order by discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM insights)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM insights
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select 
	subscription_status,
	count(customer_id) as repeated_buyers
from insights
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 

select 
	age_group,
	sum(purchase_amount) as Each_Group_Revenue
from insights
group by age_group
order by Each_Group_Revenue desc;

s